version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update -y
      - apt-get install -y openjdk-8-jdk
      - apt-get install -y maven
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region eu-west-1)
  build:
    commands:
      - mvn package
  post_build:
    commands:
      - MVN_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version)
      - docker build -t $IMAGE_REPO/$IMAGE_NAME:$MVN_VERSION .
      - docker push $IMAGE_REPO/$IMAGE_NAME:$MVN_VERSION
      - docker tag $IMAGE_REPO/$IMAGE_NAME:$MVN_VERSION $IMAGE_REPO/$IMAGE_NAME:latest
      - docker push $IMAGE_REPO/$IMAGE_NAME:latest
